### ISSUE TITLE
Two small changes for chapter 12 (webpack)

### ISSUE THREAD

**Issue by johannes-engler-mw** [carlrip/typescript-course#16]
Hi @carlrip and thanks for creating this course!

When following your descriptions in the *Using Webpack with Typescript* chapter I found that two things are not working as expected:

1. In the file **webpack.config.ts** there is an import for the dev server missing:
`import 'webpack-dev-server';`

Without there is an type error for devServer parameter.

2. When adding the **fork-ts-checker-webpack-plugin** the **eslint** parameter isn't anymore supported and has to be deleted:
```
...
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';

const config: webpack.Configuration = {
  ...,
  plugins: [
    new ForkTsCheckerWebpackPlugin({
      async: false,
    }),
  ],
};
```

With the parameter there will be an type error ;).

Maybe you can change that.

BR,

Johannes

**Comment by carlrip** [comment]
Thanks @johannes-engler-mw, I've added these changes.
